name: asset_flow
description: An application to help clients track and manage their real estate investments.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  
  # Utilities
  intl: ^0.18.1
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.6

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets like images, fonts, etc.
  #assets:
  #  - assets/images/
    
  #fonts:
  #  - family: Roboto
  #    fonts:
  #      - asset: assets/fonts/Roboto-Regular.ttf
  #      - asset: assets/fonts/Roboto-Bold.ttf
  #        weight: 700
  #      - asset: assets/fonts/Roboto-Light.ttf
  #        weight: 300