name: myapp
description: An application to help clients track and manage their real estate investments.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_data_connect: ^0.1.3+2
  table_calendar: ^3.0.9   # Add this for calendar functionality
  fl_chart: ^0.63.0        # Add this for charts
  http: ^1.1.0             # Add this for API calls
  
  #Authentication
  #google_sign_in: ^6.1.4

  # Utilities
  intl: ^0.19.0
  uuid: ^3.0.7
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_calendar_carousel: ^2.4.2
  
  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

default_connector:
  path: ./dataconnect-generated/dart/default_connector/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.6

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Assets like images, fonts, etc.
  #assets:
  #  - assets/images/
    
  #fonts:
  #  - family: Roboto
  #    fonts:
  #      - asset: assets/fonts/Roboto-Regular.ttf
  #      - asset: assets/fonts/Roboto-Bold.ttf
  #        weight: 700
  #      - asset: assets/fonts/Roboto-Light.ttf
  #        weight: 300